README.md

update rdkit channel

---

CONTRIBUTORS.md

[Community] Update Contributors

---

README.md

add links of installing pytorch and dgl

add links of installing pytorch and dgl

---

docker/install/conda_env/torch_cpu.yml
docker/install/conda_env/torch_gpu.yml
examples/reaction_prediction/rexgen_direct/README.md

Update README for Reaction Prediction and Conda Channel for RDKit

---

python/dgllife/model/gnn/attentivefp.py
python/dgllife/model/gnn/gat.py
python/dgllife/model/gnn/gcn.py
python/dgllife/model/gnn/gin.py
python/dgllife/model/gnn/mgcn.py
python/dgllife/model/gnn/mpnn.py
python/dgllife/model/gnn/schnet.py
python/dgllife/model/gnn/weave.py
python/dgllife/model/gnn/wln.py
python/dgllife/model/model_zoo/jtnn/jtmpn.py
python/dgllife/model/model_zoo/jtnn/jtnn_dec.py
python/dgllife/model/model_zoo/jtnn/jtnn_enc.py
python/dgllife/model/model_zoo/jtnn/jtnn_vae.py
python/dgllife/model/model_zoo/jtnn/mpn.py
python/dgllife/model/model_zoo/jtnn/nnutils.py
tests/model/test_gnn.py

[Model] Allow Reseting Model Parameters

---

docs/source/api/utils.mols.rst
python/dgllife/utils/featurizers.py
tests/utils/test_featurizers.py

[Utils] Atom/Bond Featurizers for AttentiveFP

---

examples/generative_models/jtnn/jtnn/datautils.py
examples/generative_models/jtnn/reconstruct_eval.py
examples/generative_models/jtnn/train.py
examples/generative_models/jtnn/vocab.py
python/dgllife/model/model_zoo/jtnn/jtnn_vae.py
python/dgllife/model/pretrain.py

1. User-defined vocabulary can be used.
2. The data set can contain monoatomic molecules.

Support Vocabulary of GuacaMol for JTNN

---

README.md
examples/generative_models/jtnn/jtnn/datautils.py

minor fix 

---

python/dgllife/data/alchemy.py
python/dgllife/data/astrazeneca_chembl_solubility.py
python/dgllife/data/esol.py
python/dgllife/data/freesolv.py
python/dgllife/data/lipophilicity.py
python/dgllife/data/pcba.py
python/dgllife/data/pdbbind.py
python/dgllife/data/pubchem_aromaticity.py
python/dgllife/data/tox21.py
python/dgllife/data/uspto.py

As reported by @cyhFlight, the package should download datasets only when they are not found.

[Dataset] Fix for Downloading Datasets

---

README.md
python/dgllife/utils/eval.py
tests/utils/test_eval.py

[Eval] Add Support for PR AUC Metric

---

README.md
conda/dgllife/meta.yaml
python/dgllife/libinfo.py

[Release] Update to version 0.2.5

---

examples/reaction_prediction/rexgen_direct/find_reaction_center_train.py
examples/reaction_prediction/rexgen_direct/utils.py
python/dgllife/data/uspto.py
python/dgllife/model/model_zoo/wln_reaction_center.py

[Rexgen] Fix for DGL 0.5

---

python/dgllife/data/csv_dataset.py

This fixes the bug reported in #102 .

[MoleculeCSVDataset] Save and Load IDs for Valid Molecules

---

docs/source/index.rst

Update Doc for Attention Visualization

---

examples/reaction_prediction/rexgen_direct/README.md
examples/reaction_prediction/rexgen_direct/candidate_ranking_eval.py
examples/reaction_prediction/rexgen_direct/candidate_ranking_train.py
examples/reaction_prediction/rexgen_direct/find_reaction_center_train.py
examples/reaction_prediction/rexgen_direct/utils.py

Hot Fix for Reaction Center Prediction

---

python/dgllife/model/gnn/__init__.py
python/dgllife/model/gnn/nf.py
python/dgllife/model/model_zoo/__init__.py
python/dgllife/model/model_zoo/nf_predictor.py
python/dgllife/model/readout/__init__.py
python/dgllife/model/readout/sum_and_max.py

Neural fingerprint was introduced in [Convolutional Networks on Graphs for Learning Molecular Fingerprints](https://arxiv.org/abs/1509.09292).

[Model] Add Neural Fingerprint

---

python/dgllife/utils/featurizers.py

*Description of changes: Docs update*

[fix] AttentiveFPBondFeaturizer

---

examples/reaction_prediction/rexgen_direct/find_reaction_center_eval.py

*Issue #127*
*Fixed bug in rexgen example to enable evaluation on CPU.*

Fixed bug in rexgen example to enable evaluation on CPU.

---

python/dgllife/utils/early_stop.py

This PR addresses the issue in #132 . See if this is what you want. @andt88

[Utils] Add Timestep in Early Stopping

---

python/dgllife/utils/featurizers.py
tests/utils/test_featurizers.py

*Issue https://github.com/awslabs/dgl-lifesci/issues/137*
*PAGTN featurizer implementation*
I will make another PR for model implementation

Adding PAGTN featurizers along with tests

---

python/dgllife/model/gnn/__init__.py
python/dgllife/model/gnn/pagtn.py
python/dgllife/model/model_zoo/__init__.py
python/dgllife/model/model_zoo/pagtn_predictor.py
tests/model/test_gnn.py
tests/model/test_property_prediction.py

*Issue https://github.com/awslabs/dgl-lifesci/issues/137*
*PAGTN Model implementation*
This is the continuation of this PR https://github.com/awslabs/dgl-lifesci/pull/138

Adding PAGTN model with tests

---

CONTRIBUTORS.md
README.md
conda/dgllife/meta.yaml
python/dgllife/libinfo.py
python/dgllife/model/gnn/gat.py

[Release] 0.2.7

---

python/dgllife/utils/splitters.py

[Split] Fix Scaffold Split

---

python/dgllife/utils/analysis.py
python/dgllife/utils/featurizers.py
python/dgllife/utils/io.py
python/dgllife/utils/jtvae/chemutils.py
python/dgllife/utils/jtvae/mol_tree.py
python/dgllife/utils/jtvae/vocab.py
python/dgllife/utils/mol_to_graph.py
python/dgllife/utils/splitters.py

Make RDKit Optional for Utils

---

python/dgllife/model/gnn/mgcn.py

Minor Fix for MGCN

---

examples/property_prediction/MTL/README.md
examples/property_prediction/MTL/configure.py
examples/property_prediction/MTL/main.py
examples/property_prediction/MTL/model/__init__.py
examples/property_prediction/MTL/model/attentivefp.py
examples/property_prediction/MTL/model/blocks.py
examples/property_prediction/MTL/model/gat.py
examples/property_prediction/MTL/model/gcn.py
examples/property_prediction/MTL/model/mpnn.py
examples/property_prediction/MTL/model/regressor.py
examples/property_prediction/MTL/run.py
examples/property_prediction/MTL/utils.py
python/dgllife/data/csv_dataset.py

[Example] Multitask Molecular Property Prediction with GNN

---

examples/property_prediction/MTL/README.md
examples/property_prediction/MTL/configure.py

[Example] Update Hyperparameters

---

docs/source/api/model.gnn.rst
docs/source/api/model.zoo.rst
docs/source/api/utils.complexes.rst
docs/source/api/utils.mols.rst
docs/source/api/utils.pipeline.rst
docs/source/cli.rst
docs/source/index.rst
docs/source/install/index.rst
python/dgllife/model/model_zoo/weave_predictor.py
python/dgllife/model/readout/weave_readout.py
python/dgllife/utils/analysis.py
python/dgllife/utils/featurizers.py

[Doc] Update

---

python/dgllife/model/model_zoo/jtvae.py

Fix the issue reported in #177

[JTVAE] Fix Issue 177

---

python/dgllife/libinfo.py

Update version to 0.3.0

---

python/dgllife/data/csv_dataset.py

[Bug Fix] Update csv_dataset.py to address #184
