awslabs/dgl-lifesci

- examples/reaction_prediction/rexgen_direct/find_reaction_center_eval.py
- python/dgllife/data/uspto.py
1. Previously we always try loading constructed DGLGraphs in `find_reaction_center_eval.py`. This may not be desired if users have multiple different files for evaluation with a same name. We now change the behavior to constructing DGLGraphs from scratch and users may choose to load existing DGLGraphs if they want.
2. Always pre-process graph edits from scratch.
> [Reaction Prediction] Fix for rexgen_direct

- examples/reaction_prediction/rexgen_direct/README.md
- examples/reaction_prediction/rexgen_direct/candidate_ranking_eval.py
- examples/reaction_prediction/rexgen_direct/candidate_ranking_train.py
- examples/reaction_prediction/rexgen_direct/find_reaction_center_eval.py
- examples/reaction_prediction/rexgen_direct/find_reaction_center_train.py
- python/dgllife/data/uspto.py
- tests/data/test_datasets.py
As suggested in #18 by @autodataming , we don't want to terminate the prediction process if some reactions cannot be properly handled by the model. With this PR, we perform a first pass to check which reactions can be handled by the model first and record reactions that cannot be handled.
> [Reaction Prediction] Handle Invalid Input Reactions

- examples/reaction_prediction/rexgen_direct/README.md
The map ids in the rxn should be consecutive!
*Issue #, if available:* #33 
> add notice for the atom map id in the rxn.

- README.md
- python/dgllife/__init__.py
- python/dgllife/model/model_zoo/__init__.py
- python/dgllife/model/model_zoo/dgmg.py
- python/dgllife/model/pretrain.py
If users only want to import some model architectures, they don't need to have RDKit installed.
> Remove the Requirement for RDKit in Importing dgllife

- python/dgllife/data/csv_dataset.py
- python/dgllife/utils/__init__.py
- python/setup.py
*Issue #, if available:* #64 
Add new arg n_jobs to MoleculeCSVDataset initialization defaulting to 1. If this is > 1, joblib is used to parallelize _pre_process.
> Add parallel processing to MoleculeCSVDataset using joblib

- python/dgllife/utils/io.py
*Issue #, if available:* None
`Chem.RemoveHs()` has an argument for whether to sanitize molecules, this is `True` by default.
However the user is allowed to specify `Sanitize=False`.
This PR uses the user-specified `sanitize` flag during molecule preprocessing. And passes it to `Chem.RemoveHs`
p.s. Nice work guys 👍
> respect sanitize molecule flag when removing hydrogens

- python/dgllife/data/csv_dataset.py
Updated an outdated import from dgl to point to dgl.data.utils where the save_graphs and load_graphs packages now live according to https://docs.dgl.ai/en/0.4.x/api/python/data.html#utils
> Update import from dgl to dgl.data.utils

- python/dgllife/model/gnn/gcn.py
- python/dgllife/model/model_zoo/gcn_predictor.py
As @haozhu233 suggested in #113 , "It might be a good idea to make it a function parameter though. People will notice this deviation from default more easily without going through the code."
> Make the message passing normalizer an argument for GCN

- examples/reaction_prediction/rexgen_direct/README.md
- examples/reaction_prediction/rexgen_direct/clean.sh
> Add Script for Cleaning up Cached Local Files for Reaction Prediction

- examples/reaction_prediction/rexgen_direct/find_reaction_center_train.py
- python/dgllife/data/uspto.py
- python/dgllife/model/model_zoo/gin_predictor.py
- python/dgllife/model/readout/sum_and_max.py
- tests/model/test_property_prediction.py
- tests/model/test_readout.py
For USPTO, constructing all molecular graphs and caching them at once can be too costly for users' machines.
> Disable Caching Molecular Graphs by Default

- examples/reaction_prediction/rexgen_direct/utils.py
*Issue #130*
In rexgen example: Enable training on CUDA-supporting maching and evaluation on non-CUDA-supporting machine.
> In rexgen example: Enable training on GPU and evaluation on CPU

- examples/reaction_prediction/rexgen_direct/candidate_ranking_train.py
- examples/reaction_prediction/rexgen_direct/utils.py
- python/dgllife/data/uspto.py
- python/dgllife/model/gnn/wln.py
- tests/model/test_gnn.py
In dgllife: Enable graphs without edges in WLN.
*Issue #134*
In rexgen example: Enabled reactant and product graphs that have no edges. This required changes in core (USPTO set and WLN model).  
> In rexgen example: Enabled reactants and products without bonds.

- python/dgllife/model/gnn/gat.py
- python/dgllife/model/model_zoo/gat_predictor.py
- python/dgllife/model/pretrain/moleculenet/bace.py
- python/dgllife/model/pretrain/moleculenet/bbbp.py
- python/dgllife/model/pretrain/moleculenet/clintox.py
- python/dgllife/model/pretrain/moleculenet/esol.py
- python/dgllife/model/pretrain/moleculenet/freesolv.py
- python/dgllife/model/pretrain/moleculenet/hiv.py
- python/dgllife/model/pretrain/moleculenet/lipophilicity.py
- python/dgllife/model/pretrain/moleculenet/muv.py
- python/dgllife/model/pretrain/moleculenet/pcba.py
- python/dgllife/model/pretrain/moleculenet/sider.py
- python/dgllife/model/pretrain/moleculenet/tox21.py
- python/dgllife/model/pretrain/moleculenet/toxcast.py
There's a bug in `GATConv` as of DGL 0.6.1 that the module tries to reset bias even when `bias=False`. While this has been fixed in the master branch of DGL, users can easily encounter the issue with DGL 0.6.1.
> [Model] Set Bias to be True by default for GAT and GATPredictor

- examples/property_prediction/ogbg_ppa/main.py
The batch of graphs does not get placed to `device` and so fails when using GPU.
Set the proper device placement.
> Fix device placement in ogbg_ppa graph property prediction example

- examples/reaction_prediction/rexgen_direct/candidate_ranking_train.py
Issue #171 
Description: Changed the default value of ```num-processes``` to 1 to avoid possible hardware problems loading the USPTO dataset
> Update default number of processes to 1

- python/setup.py
Scikit-Learn does not support python 3.6 since 1.0
> Update Version Requirement of Scikit-Learn

- python/setup.py
It doesn’t matter for you that scikit-learn 1.x doesn’t support Python 3.6 anymore. Their metadata will automatically prevent installation on that Python version.
What does matter is that there’s no reason for you to prevent installation of scikit-learn>=1.0
> unpin scikit-learn version

- CONTRIBUTORS.md
- python/dgllife/model/gnn/gat.py
- python/dgllife/model/gnn/gcn.py
This adds the `allow_zero_in_degree` option to be set in the model. This option exists in the base dgl layer objects. This change just adds the option to the GCN and GAT constructors to pass it down to the dgl layer.
> Add allow_zero_in_degree option for gat and gcn models

- CONTRIBUTORS.md
- python/dgllife/utils/featurizers.py
On a batch scale, featurizer loading turned out to be a significant bottleneck.
https://github.com/awslabs/dgl-lifesci/issues/205
Load and cache mol featurizer at init time so that it can be reused.
> Cache mol featurizer at init time

- python/dgllife/utils/complex_to_graph.py
```
cd examples/binding_affinity_prediction
python3 main.py  -m PotentialNet -d PDBBind_core_pocket_random
...
FutureWarning: In the future `np.long` will be defined as the corresponding NumPy scalar.
]).astype(np.long)
multiprocessing.pool.RemoteTraceback: 
"""
Traceback (most recent call last):
File "/usr/local/lib/python3.9/multiprocessing/pool.py", line 125, in worker
result = (True, func(*args, **kwds))
File "/usr/local/lib/python3.9/multiprocessing/pool.py", line 51, in starmapstar
return list(itertools.starmap(args[0], args[1]))
File "venv/lib/python3.9/site-packages/dgllife/utils/complex_to_graph.py", line 193, in PN_graph_construction_and_featurization
]).astype(np.long)
File "venv/lib/python3.9/site-packages/numpy/__init__.py", line 320, in __getattr__
raise …
```
> Remove np.long which is no longer supported in latest numpy
